### ISSUE TITLE
java.lang.NullPointerException:  android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()

### ISSUE THREAD

**Issue by monakhv** [bignerdranch/expandable-recycler-view#176]
Hi!
I've the following stack trace some times whene calling notifyParentItemChanged(i)

`
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
            at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3051)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2914)
            at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1447)
            at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
            at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:285)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

Could it be by any chance some bug of expandable-recycler-view? 
The situation is reproduce for both 23.2.0 and 23.1.1 versions of support library using latest 
2.1.1 version of expandable-recycler-view.

**Comment by paul-turner** [comment]
Hi @monakhv,
Yes it could be a bug for expandable-recycler-view, by any chance do you have more details on how to reproduce the bug or maybe a small sample (or editing the current sample projects). Thanks for the help!
