### ISSUE TITLE
Exception while inflating <vector>

### ISSUE THREAD

**Issue by winsontan520** [bignerdranch/expandable-recycler-view#184]
I check out the library and run the sample app but crash on launch

`03-24 10:27:15.187 20480-20480/? E/VdcInflateDelegate: Exception while inflating <vector>
                                                       org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                           at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                           at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                           at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                           at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:829)
                                                           at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:303)
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:178)
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                           at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                           at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                           at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                           at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379)
                                                           at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
                                                           at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                           at com.ryanbrooks.expandablerecyclerviewsample.MainActivity.onCreate(MainActivity.java:29)
                                                           at android.app.Activity.performCreate(Activity.java:5403)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357)
                                                           at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:136)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5249)
                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                           at dalvik.system.NativeStart.main(Native Method)
03-24 10:27:15.193 20480-20480/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ryanbrooks.expandablerecyclerviewsample, PID: 20480
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ryanbrooks.expandablerecyclerviewsample/com.ryanbrooks.expandablerecyclerviewsample.MainActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5249)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                       at com.ryanbrooks.expandablerecyclerviewsample.MainActivity.onCreate(MainActivity.java:29)
                                                       at android.app.Activity.performCreate(Activity.java:5403)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5249) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                       at com.ryanbrooks.expandablerecyclerviewsample.MainActivity.onCreate(MainActivity.java:29) 
                                                       at android.app.Activity.performCreate(Activity.java:5403) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5249) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
                                                       at android.content.res.Resources.loadDrawable(Resources.java:2155)
                                                       at android.content.res.Resources.loadDrawable(Resources.java:2074)
                                                       at android.content.res.Resources.getDrawable(Resources.java:706)
                                                       at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
                                                       at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
                                                       at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                       at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:379) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                       at com.ryanbrooks.expandablerecyclerviewsample.MainActivity.onCreate(MainActivity.java:29) 
                                                       at android.app.Activity.performCreate(Activity.java:5403) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5249) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                   	at android.graphics.drawab`

**Comment by winsontan520** [comment]
Found similar problem in http://stackoverflow.com/questions/35622438/update-android-support-library-to-23-2-0-cause-error-xmlpullparserexception-bin

the problem solved after changing gradle plugin to
classpath 'com.android.tools.build:gradle:1.5.0'

i can send you pull request if you want but you can change it since just one line changes
