### ISSUE TITLE
removing child item 

### ISSUE THREAD

**Issue by makleyston** [bignerdranch/expandable-recycler-view#247]
Hello, I'm doing the expandable list with a button in a child that when clicked, the child associated item should be removed from the parent. However, when I do the tests I realize that does not work correctly because when you click the last parent application is closed. I would like to understand why, therefore, I urge colleagues to show me some solution or some link. Here is a piece of code for consideration of you.

``` java
    @Override
    public void onBindChildViewHolder(final IngredientViewHolder childViewHolder, final int position, final Object childListItem) {
        Ingredient ingredient = (Ingredient) childListItem;
        childViewHolder.btn_del.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mItemList.remove(childListItem);
                notifyDataSetChanged();
            }
        });
        childViewHolder.bind(ingredient);
    }
```

**Comment by makleyston** [comment]
See another attempt I made: this version é 1.0.3. The last example is the version 2.1.1.
```

@Override
    public void onBindChildViewHolder(final ProductChildViewHolder productChildViewHolder, final int i, Object o) {
        final ProductSectionInitFair productSection = (ProductSectionInitFair) o;
productChildViewHolder.check.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                try {
                    mItemList.remove(i);
                    //notifyItemRemoved(i);
                    notifyDataSetChanged();
                }catch (Exception e){
                    e.printStackTrace();
                }
            }
        });
    }
```

The error is:
```
Handler (lm) {bf1894b} sending message to a Handler on a dead thread
                                                                      java.lang.IllegalStateException: Handler (lm) {bf1894b} sending message to a Handler on a dead thread
                                                                          at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                          at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                          at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                          at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                          at android.os.Handler.sendMessage(Handler.java:507)
                                                                          at android.os.Message.sendToTarget(Message.java:416)
                                                                          at lm.run(:com.google.android.gms.DynamiteModulesA:246)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by paul-turner** [comment]
Hello @makleyston,
I don't think that's the right exception that is causing the crash. I will note that we do not currently support `notifyDataSetChanged()` with this library, details on its support are held in #89.

You should also not be modifying `mItemList` directly, unless you also modify the `mParentItemList` as well (which is difficult to do unless you have a complete knowledge of the adapter). 

Take a look at the code in the sample for removing a child item contained here: 
https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L292

You'll want to use `notifyChildItemRemoved(int parentPos, int childPos)` and use position information relative to the parent list not the `int i` passed in to `onBindChildViewHolder` (The 3.0.0-SNAPSHOT has a better implementation of `onBindChildViewHolder` to help with this)

**Comment by avtseben** [comment]
In my Shopping List application i use ExpandableRecyclerView to group Products by Category.
Use swipe left to delete child (Product) from RecyclerView. And when swipe happens you get only
(int position) of your item, but you don't know parentPosition and childPosition in your adapter data to 
remove childItem correctly. I solve it by this method in Adapter class:
```
   public void removeChildItem(int position){
        int childPosition = 0;
        int parentPosition = 0;
        boolean parentFound = false;
        for(int i = position; i > 0; i--) {
            if(mItemList.get(i).getClass().equals(ParentWrapper.class)) {
                if(!parentFound){
                    parentFound = true;
                }
                parentPosition++;
            } else if(!parentFound) {
                childPosition++;
            }
        }
        childPosition--;
        ParentItem p = (ParentItem)getParentItemList().get(parentPosition);
        List<ProductInstance> childList = p.getChildItemList();
        childList.remove(childPosition);
        notifyChildItemRemoved(parentPosition,childPosition);
    }
```

**Comment by paul-turner** [comment]
Hi @avtseben,
Would the changes described in https://github.com/bignerdranch/expandable-recycler-view/issues/157#issuecomment-189515584 help get you the correct index?

The ParentViewHolder and ChildViewHolder now have the parent and child indices which might help remove the code that you have above. Let me know if not, would love to see where I can improve the library so you don't have to rely on implementation details of the adapter.
