### ISSUE TITLE
How to expand specific Parent?

### ISSUE THREAD

**Issue by iRYO400** [bignerdranch/expandable-recycler-view#314]
Hello @bignerdranch!
So I've found a method **expandParent(int parentIndex)**. And I tried to use it, espessially inside onBindViewHolder,
```
@Override
    public void onBindParentViewHolder(SpisokMatcheiGroupViewHolder parentViewHolder, int position, ParentListItem parentListItem) {
        MainMatchGroupModel mainMatchGroupModel = (MainMatchGroupModel) parentListItem;
        parentViewHolder.bind(mainMatchGroupModel);
        if (mainGroupModel.getPriority() <= 9000) {
            expandParent(position);
        }
    }
```

but I always get exception 
```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                                   at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2397)
                                                                   at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4634)
                                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:10472)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6248)
                                                                   at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.expandParentListItem(ExpandableRecyclerAdapter.java:637)
                                                                   at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.expandViews(ExpandableRecyclerAdapter.java:590)
                                                                   at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.expandParent(ExpandableRecyclerAdapter.java:405)
```
How can I solve it?

**Comment by iRYO400** [comment]
It was EZY-BREEZY
Solved it by adding necessary methods inside Handler

```
if (mainGroupModel.getPriority() > 9000){
            Handler handler = new Handler();
            final Runnable r = new Runnable() {
                @Override
                public void run() {
                    expandParent(position);
                }
            };
            handler.post(r);
        }
```

**Comment by paul-turner** [comment]
@iRYO400 Alternatively consider setting `isInitiallyExpanded()` to true when `mainGroupModel.getPriority() <= 9000` in your ParentListItem
