### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by kshitij-sminq** [bignerdranch/expandable-recycler-view#318]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
       at java.util.ArrayList.get(ArrayList.java:306)
       at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.parentExpandedFromViewHolder(ExpandableRecyclerAdapter.java:419)
       at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter$1.onParentExpanded(ExpandableRecyclerAdapter.java:446)
       at com.bignerdranch.expandablerecyclerview.ParentViewHolder.expandView(ParentViewHolder.java:186)
       at com.bignerdranch.expandablerecyclerview.ParentViewHolder.onClick(ParentViewHolder.java:158)
       at android.view.View.performClick(View.java:3571)
       at android.view.View$PerformClick.run(View.java:14247)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by paul-turner** [comment]
@kshitij-sminq Could you give context as to what you were doing? what was the data before and after? sample code to reproduce?
