### ISSUE TITLE
Support library update

### ISSUE THREAD

**Issue by MScudeller** [bignerdranch/expandable-recycler-view#355]
I'm having a issue that is when I update the android support libraries from 23.4.0 to either 24.2.1 or 25.3.1 the app will crash when I collapse the parent: 

```
FATAL EXCEPTION: main
Process: com.slb.miproductsqa, PID: 14339
java.lang.IllegalArgumentException: parameter must be a descendant of this view
at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5335)
at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5264)
at android.widget.HorizontalScrollView.isWithinDeltaOfScreen(HorizontalScrollView.java:1143)
at android.widget.HorizontalScrollView.onSizeChanged(HorizontalScrollView.java:1539)
at android.view.View.sizeChange(View.java:16765)
at android.view.View.setFrame(View.java:16727)
at android.view.View.layout(View.java:16643)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1139)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:833)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:847)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1197)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
at android.view.View.layout(View.java:16647)
at android.view.ViewGroup.layout(ViewGroup.java:5438)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.Z
```

**Comment by paul-turner** [comment]
Are you doing and focus/keyboard actions on expand/collapse?

**Comment by MSpades** [comment]
yes, because I need to have 2 EditText in the childViewHolder, is there anything I can do for it to work?

**Comment by paul-turner** [comment]
Seems like maybe the timing/source of those calls is the source of this. I'm not sure what are the alternatives, possibly using a different view as your source when making the call? seems like on the new support library the child views are gone and so something throws an exception. 
Not sure there is anything I can change with XRV to help here.
