### ISSUE TITLE
some times it crashes

### ISSUE THREAD

**Issue by stasbar** [bignerdranch/expandable-recycler-view#84]
Hello. I'm using your adapter in my app (2.0 SNAPSHOT cuz I need isInitiallyExpanded() {
        return true; in my case). And some times it crash

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
            at android.view.LayoutInflater.from(LayoutInflater.java:219)
            at com.stasbar.gabi4k.MyExpandableAdapter.<init>(MyExpandableAdapter.java:42)
            at com.stasbar.gabi4k.fragments.CategoryFragment.setList(CategoryFragment.java:49)
            at com.stasbar.gabi4k.fragments.presenters.CategoryPresenter$1.success(CategoryPresenter.java:37)
            at com.stasbar.gabi4k.fragments.presenters.CategoryPresenter$1.success(CategoryPresenter.java:28)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by paul-turner** [comment]
@stasbar I don't see any expandable adapter code from the library (only your subclass). Could you share more of what's going on in `MyExpandableAdapter.java:42`?

**Comment by stasbar** [comment]
Yes, sorry. It happens in constructor.
    private LayoutInflater mInflater;
    private Context context;
    private Drawable placeholder;
public MyExpandableAdapter(Context context, List<? extends ParentListItem> parentItemList) {
        super((List<ParentListItem>) parentItemList);
        this.context = context;
        mInflater = LayoutInflater.from(this.context); // Here

        Bitmap.Config conf = Bitmap.Config.ALPHA_8;
        placeholder = new GlideBitmapDrawable(context.getResources(), Bitmap.createBitmap(120, 120, conf));
    }

**Comment by paul-turner** [comment]
@stasbar it is likely that you are passing in a null Context into the constructor. Your async code is probably coming back to a dead activity (due to rotation is my best guess).

**Comment by stasbar** [comment]
Yeah. You are right. I did null check on context and it seems to stop crashing. Thanks Man :)
